### ISSUE TITLE
Status that an event is held online ?

### ISSUE THREAD

**Issue by TheFive** [thomersch/openstreetmap-calendar#49] opened 2020-11-28 17:41 UTC
Hi some people use the venue field with "online" or another word to indicate a meeting is virtual in the venue field.

Does it make sense to reflect the pandemic by a special online field ?

current weeklyOSM integration (beta status) is doing that base on the "online" word usage in the wiki calendar.

At the end OSMCAL users can filter on Events in Germany, or online events (e.g. show me all online events in NRW, to have regional infos but no travel).

**Comment by thomersch** [comment] 2020-11-29 12:28
Duplicate of #44

**Closed by thomersch** 2020-11-29 12:28 UTC
