### ISSUE TITLE
country flags

### ISSUE THREAD

**Issue by dieterdreist** [thomersch/openstreetmap-calendar#99] opened 2022-04-06 15:12 UTC
The new calendar is great, way more easy and convenient compared to the former wiki source code copy, paste and modify operations. As a minor nitpick, and maybe due to technical reasons, there are no more flags in the list. I found these flags very helpful to get an impression about events happening in my country and where in general the community is very active.
To get an idea about the kind of activity, also the event type icons were useful, but less important than the flags IMHO.
Is there a chance you are going to implement these? Has it to do with wiki loading times on pages with many images?

**Comment by thomersch** [comment] 2022-04-06 20:54
Duplicate of #46

**Closed by thomersch** 2022-04-06 20:54 UTC
