### ISSUE TITLE
Transform time to my local timezone

### ISSUE THREAD

**Issue by tordans** [thomersch/openstreetmap-calendar#152] opened 2024-01-10 16:31 UTC
Right now, an event like https://osmcal.org/event/2528/ says 
> 10th January 16:30 (Etc/UTC)

It would be great, if the app could transform this into my local time.
AFAIK javascript should be able to do this. It just needs to know my local time zone. 

To get my local time zone, the app could show a dropdown and store the selected value in a cookie. Or maybe derive it from data in my OSM user profile.

**Comment by danieldegroot2** [comment] 2024-01-12 10:29
Duplicate of https://github.com/thomersch/openstreetmap-calendar/issues/45

**Closed** 2024-01-14 21:03 UTC
